/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // EXACT Anthropic spec — VERIFIED tokens (no inferred values)
        slateDark: "#141413",
        ivoryMedium: "#f0eee6",
        ivoryLight: "#faf9f5",
        cloudMedium: "#b0aea5",
        cloudDark: "#87867f",
        stone: "#cccbc8",
        slateMedium: "#3d3d3a",
        oatWarm: "#e3dacc",
        manilla: "#f5e3c7",
        clay: "#d97757",
        clayDeep: "#c6613f",
        // CSS-var aliases (kebab via bracket access if needed)
        "slate-dark": "#141413",
        "ivory-medium": "#f0eee6",
        "ivory-light": "#faf9f5",
        "cloud-medium": "#b0aea5",
        "cloud-dark": "#87867f",
        "oat-warm": "#e3dacc",
        "clay-deep": "#c6613f",
        // legacy aliases — remapped to exact tokens so old classes still compile
        bgPrimary: "#f0eee6",
        bgSecondary: "#faf9f5",
        bgMuted: "#e3dacc",
        fgPrimary: "#141413",
        fgSecondary: "#87867f",
        fgMuted: "#b0aea5",
        accent: "#d97757",
        accentHover: "#c6613f",
        accentSubtle: "#f5e3c7",
        accentBorder: "#cccbc8",
        border: "#cccbc8",
        borderStrong: "#87867f",
        success: "#141413",
        error: "#c6613f",
        warn: "#87867f",
        accent2: "#d97757",
        accent3: "#141413",
      },
      fontFamily: {
        anthropicSerif: ["'Anthropic Serif'", "ui-serif", "Georgia", "Cambria", "Times", "serif"],
        anthropicSans: ["'Anthropic Sans'", "ui-sans-serif", "system-ui", "sans-serif"],
        anthropicMono: ["ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
        // legacy aliases
        tiempos: ["'Anthropic Serif'", "ui-serif", "Georgia", "Cambria", "Times", "serif"],
        inter: ["'Anthropic Sans'", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
        serif: ["'Anthropic Serif'", "ui-serif", "Georgia", "Cambria", "Times", "serif"],
        sans: ["'Anthropic Sans'", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "1.40", letterSpacing: "-0.24px" }],
        "body-sm": ["16px", { lineHeight: "1.00", letterSpacing: "-0.08px" }],
        body: ["20px", { lineHeight: "1.40" }],
        subheading: ["24px", { lineHeight: "1.30", letterSpacing: "-0.05px" }],
        heading: ["61px", { lineHeight: "1.10", letterSpacing: "-0.12px" }],
        display: ["68px", { lineHeight: "1.10" }],
        mono: ["16px", { lineHeight: "1.40" }],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        6: "24px",
        8: "32px",
        19: "76px",
        25: "100px",
      },
      borderRadius: {
        card: "24px",
        "btn-filled": "8px",
        "btn-outlined": "12px",
        nav: "0px",
        link: "0px",
        badge: "0px",
        sm: "12px",
        DEFAULT: "12px",
        lg: "12px",
        xl: "24px",
        "2xl": "24px",
        "3xl": "24px",
        pill: "12px",
      },
      maxWidth: {
        page: "1280px",
        prose: "65ch",
      },
      letterSpacing: {
        caption: "-0.24px",
        "body-sm": "-0.08px",
        subheading: "-0.05px",
        heading: "-0.12px",
        anthropic: "-0.02em",
        label: "-0.24px",
      },
      lineHeight: {
        caption: "1.40",
        "body-sm": "1.00",
        body: "1.40",
        subheading: "1.30",
        heading: "1.10",
        display: "1.10",
        anthropic: "1.10",
      },
      // Elevation: NONE — no shadows, flat via surface tone + 1px borders only
      boxShadow: {
        none: "none",
      },
    },
  },
  plugins: [],
};
